#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEMO="$ROOT/scripts/demo.sh"

grep -q 'Doctor: remediation hint JSON' "$DEMO"
grep -q 'zmr doctor --json' "$DEMO"
grep -q 'definitely-missing-android-shim' "$DEMO"
grep -q 'setup.android_shim.not_found' "$DEMO"
grep -q '"hint"' "$DEMO"
grep -q 'Run npx zmr-install-android-shim' "$DEMO"
grep -q 'Doctor: no ready devices diagnostics' "$DEMO"
grep -q 'setup.android.no_devices' "$DEMO"
grep -q 'setup.ios.no_booted_simulators' "$DEMO"
grep -q 'zmr doctor --strict --json' "$DEMO"
grep -q 'expected doctor --strict to fail' "$DEMO"
grep -q 'zmr devices --json --adb' "$DEMO"
grep -q 'zmr devices --json --platform ios' "$DEMO"
grep -q 'Doctor: config field diagnostics' "$DEMO"
grep -q 'demo-bad-config.json' "$DEMO"
grep -q 'config.empty_string' "$DEMO"
grep -q 'fieldPath' "$DEMO"
grep -q '$.scripts.android' "$DEMO"
grep -q 'Doctor: config smoke scenario checks' "$DEMO"
grep -q 'ios-smoke-scenario' "$DEMO"
grep -q 'ios.smokeScenario' "$DEMO"
grep -q 'demo-invalid-smoke-scenario.json' "$DEMO"
grep -q 'scenario.invalid' "$DEMO"
grep -q 'Run zmr validate on the configured Android smoke scenario' "$DEMO"
grep -q 'Init an app-local .zmr workspace' "$DEMO"
grep -q 'zmr init --app --json --dir traces/demo-init-app' "$DEMO"
grep -q 'Import a mobile-flow YAML scenario' "$DEMO"
grep -q 'zmr import flow-yaml traces/demo-flow-yaml-flow.yaml' "$DEMO"
grep -q 'zmr validate traces/demo-imported-flow.json' "$DEMO"
grep -q 'doctor --strict --json' "$DEMO"
grep -q 'zmr run examples/demo-fake.json' "$DEMO"
grep -q -- '--json' "$DEMO"
grep -q 'Run Go reference client against fake ZMR server' "$DEMO"
grep -q 'go run ./examples/fake-session' "$DEMO"
grep -q 'Run Rust reference client against fake ZMR server' "$DEMO"
grep -q 'cargo run --quiet' "$DEMO"
